### ISSUE TITLE
albedo.F90

### ISSUE THREAD

**Issue by trondkr** [kshedstrom/roms#1]
Hi Kate. Seems variable for albedo over ocean 'alb_w' is not defined unless you are running ROMS with the ice model. In albedo.F90 I had to move 

real(r8), parameter :: alb_w=0.06_r8

outside of the ifdefs:
ifdef ICE_BULK_FLUXES
ifdef ALBEDO_CSIM

**Comment by kshedstrom** [comment]
Ah, right you are. Thanks!
