### ISSUE TITLE
Bug in calculation of grid spacing in roms_to_pop.py

### ISSUE THREAD

**Issue by christophrenkl** [kshedstrom/roms#12]
I just discovered a bug in the python program `roms_to_pop.py` that is used to create a model grid file for CICE based on a ROMS grid. Lines 50-53 read:
```
htn = 0.5*(dy[1:-1,1:-1] + dy[2:,1:-1])
hus = 0.5*(dx[1:-1,1:-1] + dx[1:-1,2:])
hte = 0.5*(dy[1:-1,1:-1] + dy[1:-1,2:])
huw = 0.5*(dx[1:-1,1:-1] + dx[2:,1:-1])
```
Based on the CICE documentation, the variable `htn` is the "length of northern edge (Δx) of T-cell", however, in the code above it is set to the Δy of the ROMS grid. This should not matter too much if the grid cells are approximately square in a kilometer sense, but will make a difference if the grid cells are more rectangular.

**Comment by kshedstrom** [comment]
Thanks, yes, you are right. Fixed.
