### ISSUE TITLE
Potential tides - not reading from forcing file

### ISSUE THREAD

**Issue by slhowardESR** [kshedstrom/roms#9]
Hi Kate,

I am not sure whether this is an issue or just a change in how things are done between 3.7 and 3.6.

I am currently using stefanie mack's 3.7 branch (with ice shelves in it) but it was based off of your branch.  And it looks like it has the potential tide code in it, but I can't get it to read the tide forcing file properly.

I was wondering if you have run a model using potential tides using your version of the roms3.7 model?  

The tide forcing file I use works in 3.6.  and it looks like it can't be read in the 3.7 version. 
It fails when it should be reading in the potential tide amp:  From the *.out file

        GET_2DFLD   - maximum tidal current, ellipse major axis
                       (Grid = 01, Min =  0.00000000E+00 Max =  2.01598481E+01)
       GET_2DFLD   - minimum tidal current, ellipse minor axis
                       (Grid = 01, Min = -2.97327515E+00 Max =  2.01632515E+00)

     INQUIRY     - unable to find requested variable: \00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00\00

In the 3.6 code,  it reads it in and it all works well.

    GET_2DFLD   - maximum tidal current, ellipse major axis
                   (Min =  0.00000000E+00 Max =  2.02808533E+01)
    GET_2DFLD   - minimum tidal current, ellipse minor axis
                   (Min = -2.97327515E+00 Max =  2.16472321E+00)
    GET_2DFLD   - tidal potential elevation amplitude
                   (Min =  0.00000000E+00 Max =  1.23815612E-01)
    GET_2DFLD   - tidal potential elevation phase angle
                   (Min =  0.00000000E+00 Max =  6.28318517E+00)

I will keep looking at this more see if I can tell what is going on in the code, but wanted to know if you had any ideas, and to see whether you have successfully used potential tide with roms3.7.

**Comment by kshedstrom** [comment]
Hi Susan,

I believe my Arctic domain uses potential tides, no problem. I’m in
hospital where checking isn’t that convenient, sorry.

**Comment by slhowardESR** [comment]
Oh No Kate!  So sorry to hear. 
I hope you get well soon!

And I will play with things on my own and not bug you!  but I will post if I figure out what is going on, if I find anything helpful. 

take care!

**Comment by slhowardESR** [comment]
Actually, silly mistake on my part.  Pamp and Pphase were not in my varinfo,dat.   So disregard this whole thread.    And thanks!
